#pragma once

#define RPC_OK 0
#define RPC_ERROR_NOT_AUTHENTICATED 1
#define RPC_ERROR_NO_LICENSE 2
#define RPC_ERROR_INVALID_CREDENTIALS 3
#define RPC_ERROR_ACTIVATION_FAILED 4
#define RPC_ERROR_NETWORK 5
#define RPC_ERROR_INTERNAL 6